//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_WEEK02_DatabasesFirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FIT5032_WEEK02_DatabasesFirstEntities3 : DbContext
    {
        public FIT5032_WEEK02_DatabasesFirstEntities3()
            : base("name=FIT5032_WEEK02_DatabasesFirstEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Student> Students { get; set; }
        public DbSet<Unit> Units { get; set; }
    }
}
